language: node_js
node_js:
  - '20'

cache:
  directories:
    - ".eslintcache"
    - "$HOME/.pnpm-store"

notifications:
  email: false

before_install:
  - npm install --global pnpm

script:
  - pnpm run fmt --check
  - pnpm exec tsc --noEmit
  - pnpm run test:ci

branches:
  only: master
